code_lines = [
    '"""Node 1: Query Parser Node.',
    'Phân tích câu hỏi tài chính thành cấu trúc JSON chuẩn.',
    'Output format: ten_cong_ty, so_nam, noi_dung, thao_tac (muc_tieu: trich_xuat | so_sanh), tieu_chi_phu.',
    'Không thực hiện tìm bảng — việc này do Data Discovery xử lý.',
    '"""',
    '',
    'import re',
    'import time',
    'import yaml',
    'from pathlib import Path',
    'from typing import Dict, Any, Optional, List, Tuple, Set',
    'import pandas as pd',
    'from langchain_core.messages import SystemMessage, HumanMessage',
    '',
    'from pipeline.src.state import AgentState',
    'from pipeline.src.config import Config, config as default_config',
    'from pipeline.src.llm_provider import get_llm',
    'from pipeline.src.utils.json_repair import safe_parse_json',
    '',
    '',
    'def load_query_parser_prompt(cfg: Config) -> Dict[str, Any]:',
    '    """Load prompt templates and few-shot examples from YAML."""',
    '    prompt_path = cfg.get_prompt_path("query_parser.yaml")',
    '    if not prompt_path.exists():',
    '        raise FileNotFoundError(f"Prompt file not found at: {prompt_path}")',
    '',
    '    with open(prompt_path, "r", encoding="utf-8") as f:',
    '        return yaml.safe_load(f)',
    '',
    '',
    'NEGATIVE_BLOCKLIST: Set[str] = {',
    '    # Corporate prefixes / legal forms',
    '    "CTCP", "TMCP", "TẬP ĐOÀN", "CÔNG TY", "NGÂN HÀNG", "TỔNG CÔNG TY",',
    '    "TNHH", "CP", "DN", "JSC", "CORP", "CORPORATION", "GROUP", "BANK",',
    '    "HOLDINGS", "SECURITIES", "CHỨNG KHOÁN", "BẢO HIỂM", "BẤT ĐỘNG SẢN",',
    '    # Financial report terms & abbreviations',
    '    "BÁO CÁO", "TÀI CHÍNH", "BCTC", "TCTD", "TNDN", "TNCN", "GTGT", "VAMC",',
    '    "CHKQT", "CHK", "HĐQT", "HDQT", "TSCĐ", "TSCD", "SXKD", "XDCB",',
    '    # Generic domain words',
    '    "VIỆT NAM", "QUỐC TẾ", "ĐẦU TƯ", "THƯƠNG MẠI", "XÂY DỰNG", "NĂNG LƯỢNG",',
    '    # Currencies & exchanges',
    '    "VND", "USD", "EUR", "HOSE", "HNX", "UPCOM", "VN30", "VNINDEX",',
    '}',
    '',
    'ALIAS_TICKER_MAP: Dict[str, str] = {',
    '    # Real Estate & Construction',
    '    "địa ốc no va": "NVL",',
    '    "đầu tư địa ốc no va": "NVL",',
    '    "tập đoàn đầu tư địa ốc no va": "NVL",',
    '    "novaland": "NVL",',
    '    "nova": "NVL",',
    '    "hạ tầng giao thông đèo cả": "HHV",',
    '    "giao thông đèo cả": "HHV",',
    '    "đèo cả": "HHV",',
    '    "đức long gia lai": "DLG",',
    '    "vincom retail": "VRE",',
    '    "vingroup": "VIC",',
    '    "đất xanh": "DXG",',
    '    "bất động sản đất xanh": "DXS",',
    '    "nam long": "NLG",',
    '    "phát đạt": "PDR",',
    '    "kinh bắc": "KBC",',
    '    "hà đô": "HDG",',
    '    "hòa bình": "HBC",',
    '    "xây dựng hòa bình": "HBC",',
    '    "sunshine homes": "SSH",',
    '    "sunshine": "SSH",',
    '    "bất động sản thế kỷ": "CRE",',
    '    "cenland": "CRE",',
    '    "bất động sản văn phú": "VPI",',
    '    "văn phú invest": "VPI",',
    '    "khải hoàn land": "KHG",',
    '    "hải phát": "HPX",',
    '    "tasco": "HUT",',
    '    "sông đà": "SJG",',
    '    "sonadezi": "SNZ",',
    '    "becamex ijc": "IJC",',
    '',
    '    # Banking & Finance',
    '    "an bình": "ABB",',
    '    "ab bank": "ABB",',
    '    "abbank": "ABB",',
    '    "á châu": "ACB",',
    '    "bắc á": "BAB",',
    '    "baca bank": "BAB",',
    '    "đầu tư và phát triển việt nam": "BID",',
    '    "bidv": "BID",',
    '    "bảo việt": "BVH",',
    '    "tập đoàn bảo việt": "BVH",',
    '    "công thương việt nam": "CTG",',
    '    "vietinbank": "CTG",',
    '    "xuất nhập khẩu việt nam": "EIB",',
    '    "eximbank": "EIB",',
    '    "phát triển thành phố hồ chí minh": "HDB",',
    '    "hdbank": "HDB",',
    '    "kiên long": "KLB",',
    '    "kienlongbank": "KLB",',
    '    "quân đội": "MBB",',
    '    "mbbank": "MBB",',
    '    "hàng hải việt nam": "MSB",',
    '    "nam á": "NAB",',
    '    "nama bank": "NAB",',
    '    "quốc dân": "NVB",',
    '    "ncb": "NVB",',
    '    "phương đông": "OCB",',
    '    "sài gòn công thương": "SGB",',
    '    "saigonbank": "SGB",',
    '    "sài gòn - hà nội": "SHB",',
    '    "shb": "SHB",',
    '    "đông nam á": "SSB",',
    '    "seabank": "SSB",',
    '    "sài gòn thương tín": "STB",',
    '    "sacombank": "STB",',
    '    "sài gòn tài lộc": "STB",',
    '    "việt á": "VAB",',
    '    "viet a bank": "VAB",',
    '    "ngoại thương việt nam": "VCB",',
    '    "vietcombank": "VCB",',
    '    "quốc tế việt nam": "VIB",',
    '    "việt nam thịnh vượng": "VPB",',
    '    "vpbank": "VPB",',
    '    "evn finance": "EVF",',
    '',
    '    # Securities',
    '    "chứng khoán fpt": "FTS",',
    '    "chứng khoán mb": "MBS",',
    '    "chứng khoán ssi": "SSI",',
    '',
    '    # Technology & Telecommunications',
    '    "fpt": "FPT",',
    '    "viễn thông fpt": "FOX",',
    '    "fpt telecom": "FOX",',
    '',
    '    # Retail & Consumer Goods',
    '    "thế giới di động": "MWG",',
    '    "sữa việt nam": "VNM",',
    '    "vinamilk": "VNM",',
    '    "sabeco": "SAB",',
    '    "bia sài gòn": "SAB",',
    '    "masan": "MSN",',
    '    "tập đoàn masan": "MSN",',
    '    "hàng tiêu dùng masan": "MCH",',
    '    "masan consumer": "MCH",',
    '    "masan meatlife": "MML",',
    '    "masan high-tech materials": "MSR",',
    '    "vàng bạc đá quý phú nhuận": "PNJ",',
    '    "pnj": "PNJ",',
    '    "đường quảng ngãi": "QNS",',
    '    "vinasoy": "QNS",',
    '    "dabaco": "DBC",',
    '',
    '    # Energy, Industry & Materials',
    '    "hòa phát": "HPG",',
    '    "hoa sen": "HSG",',
    '    "nam kim": "NKG",',
    '    "xăng dầu việt nam": "PLX",',
    '    "petrolimex": "PLX",',
    '    "lọc hóa dầu việt nam": "BSR",',
    '    "lọc dầu bình sơn": "BSR",',
    '    "bình sơn": "BSR",',
    '    "khí việt nam": "GAS",',
    '    "pv gas": "GAS",',
    '    "điện lực dầu khí": "POW",',
    '    "pv power": "POW",',
    '    "vận tải dầu khí": "PVT",',
    '    "pvtrans": "PVT",',
    '    "phân bón dầu khí cà mau": "DCM",',
    '    "đạm cà mau": "DCM",',
    '    "phân bón và hóa chất dầu khí": "DPM",',
    '    "đạm phú mỹ": "DPM",',
    '    "cao su việt nam": "GVR",',
    '    "công nghiệp cao su việt nam": "GVR",',
    '    "cảng hàng không việt nam": "ACV",',
    '    "cảng hàng không quốc tế": "ACV",',
    '    "hàng không vietjet": "VJC",',
    '    "vietjet": "VJC",',
    '    "vietjet air": "VJC",',
    '    "dệt may việt nam": "VGT",',
    '    "vinatex": "VGT",',
    '    "viglacera": "VGC",',
    '    "gelex": "GEX",',
    '    "tập đoàn gelex": "GEX",',
    '    "điện lực gelex": "GEE",',
    '    "gelex electric": "GEE",',
    '    "điện gia lai": "GEG",',
    '    "nhiệt điện hải phòng": "HND",',
    '    "điện lực tkv": "DTK",',
    '    "thủy điện đa nhim": "DNH",',
    '    "tập đoàn pc1": "PC1",',
    '    "xây lắp điện 1": "PC1",',
    '    "vicem hà tiên": "HT1",',
    '    "xi măng vicem hà tiên": "HT1",',
    '    "xi măng hà tiên": "HT1",',
    '    "hà tiên 1": "HT1",',
    '    "nhựa an phát xanh": "AAA",',
    '    "an phát xanh": "AAA",',
    '    "an phát": "AAA",',
    '    "thủy sản minh phú": "MPC",',
    '    "minh phú": "MPC",',
    '    "sao mai": "ASM",',
    '    "tập đoàn sao mai": "ASM",',
    '    "hoàng anh gia lai": "HAG",',
    '    "hagl": "HAG",',
    '    "nông nghiệp quốc tế hoàng anh gia lai": "HNG",',
    '    "hagl agrico": "HNG",',
    '    "nông nghiệp baf": "BAF",',
    '    "baf việt nam": "BAF",',
    '    "container việt nam": "VSC",',
    '    "viconship": "VSC",',
    '    "lương thực miền nam": "VSF",',
    '    "vinafood 2": "VSF",',
    '    "vinafood ii": "VSF",',
    '    "lâm nghiệp việt nam": "VIF",',
    '    "vinafor": "VIF",',
    '    "đại dương": "OGC",',
    '    "tập đoàn đại dương": "OGC",',
    '    "sam holdings": "SAM",',
    '    "gỗ trường thành": "TTF",',
    '}',
    '',
    '_CACHED_NAME_TO_CODE: Optional[List[Tuple[str, str]]] = None',
    '_CACHED_ALL_TICKERS: Optional[Set[str]] = None',
    '',
    '',
    'def _get_stock_mappings() -> Tuple[List[Tuple[str, str]], Set[str]]:',
    '    """Load and cache (name_to_code, all_tickers) from code_stock.csv."""',
    '    global _CACHED_NAME_TO_CODE, _CACHED_ALL_TICKERS',
    '    if _CACHED_NAME_TO_CODE is not None and _CACHED_ALL_TICKERS is not None:',
    '        return _CACHED_NAME_TO_CODE, _CACHED_ALL_TICKERS',
    '',
    '    name_to_code: List[Tuple[str, str]] = []',
    '    all_tickers: Set[str] = set()',
    '',
    '    possible_paths = [',
    '        Path("rag_module/code_stock.csv"),',
    '        Path("rag_module/ViFinQA/code_stock.csv"),',
    '        Path("/kaggle/working/r2AI_2026/rag_module/code_stock.csv"),',
    '        Path(__file__).resolve().parent.parent.parent / "rag_module" / "code_stock.csv",',
    '        Path(__file__).resolve().parent.parent.parent / "rag_module" / "ViFinQA" / "code_stock.csv",',
    '    ]',
    '',
    '    csv_path = None',
    '    for p in possible_paths:',
    '        if p.exists():',
    '            csv_path = p',
    '            break',
    '',
    '    if csv_path:',
    '        try:',
    '            df = pd.read_csv(csv_path, encoding="utf-8-sig", dtype=str)',
    '            ticker_col = next((c for c in df.columns if "CK" in c.upper()), df.columns[0])',
    '            name_col = next((c for c in df.columns if "TÊN" in c.upper() or "TEN" in c.upper()), df.columns[1])',
    '',
    '            for _, row in df.iterrows():',
    '                code = str(row[ticker_col]).strip().upper() if pd.notna(row[ticker_col]) else ""',
    '                name = str(row[name_col]).strip() if pd.notna(row[name_col]) else ""',
    '                if code:',
    '                    all_tickers.add(code)',
    '                if code and name:',
    '                    name_to_code.append((name, code))',
    '                    clean_name = re.sub(',
    '                        r"\\b(CTCP|Tập đoàn|Công ty|Cổ phần|Ngân hàng|TMCP|\\-\\s*CTCP|Tổng Công ty|TNHH)\\b",',
    '                        "",',
    '                        name,',
    '                        flags=re.IGNORECASE',
    '                    ).strip(" -")',
    '                    if clean_name and clean_name.lower() != name.lower() and len(clean_name) >= 3:',
    '                        name_to_code.append((clean_name, code))',
    '        except Exception as e:',
    '            print(f"⚠️ [Query Parser] Error loading code_stock.csv: {e}")',
    '    else:',
    '        try:',
    '            from rag_module.search_engine import _ensure_resources, _company_map',
    '            _ensure_resources()',
    '            if _company_map:',
    '                name_to_code = list(_company_map)',
    '                all_tickers = {code.upper() for _, code in _company_map}',
    '        except Exception:',
    '            pass',
    '',
    '    _CACHED_NAME_TO_CODE = name_to_code',
    '    _CACHED_ALL_TICKERS = all_tickers',
    '    return _CACHED_NAME_TO_CODE, _CACHED_ALL_TICKERS',
    '',
    '',
    'def _normalize_company_name(company_input: str, user_query: str) -> str:',
    '    """Normalize company name or raw ticker input against brand aliases and code_stock.csv.',
    '',
    '    Resolution Precedence:',
    '    1. Filter out corporate prefix blocklist (CTCP, TMCP, Tập đoàn...).',
    '    2. Check explicit parentheses ticker in query: (TICKER), e.g. (VJC), (NVL), (HHV).',
    '    3. Check ALIAS_TICKER_MAP (sorted by length descending).',
    '    4. Check company names from code_stock.csv (sorted by length descending, including clean names).',
    '    5. Check standalone uppercase 3-5 letter words in query against all_tickers (excluding NEGATIVE_BLOCKLIST).',
    '    6. Validate fallback company_input from LLM.',
    '    """',
    '    company_input = company_input.strip() if company_input else ""',
    '    user_query = user_query.strip() if user_query else ""',
    '    q_lower = user_query.lower()',
    '',
    '    if company_input.upper() in NEGATIVE_BLOCKLIST:',
    '        company_input = ""',
    '',
    '    name_to_code, all_tickers = _get_stock_mappings()',
    '',
    '    # Priority 1: Check explicit parenthesized ticker: (TICKER)',
    '    paren_match = re.search(r"\\(([A-Za-z]{2,5})\\)", user_query)',
    '    if paren_match:',
    '        paren_code = paren_match.group(1).upper()',
    '        if paren_code in all_tickers and paren_code not in NEGATIVE_BLOCKLIST:',
    '            return paren_code',
    '',
    '    # Priority 2: Check ALIAS_TICKER_MAP (longest alias match first)',
    '    sorted_aliases = sorted(ALIAS_TICKER_MAP.items(), key=lambda x: len(x[0]), reverse=True)',
    '    for alias_name, alias_ticker in sorted_aliases:',
    '        if alias_name in q_lower:',
    '            return alias_ticker',
    '',
    '    # Priority 3: Check registered company names from code_stock.csv (longest name first)',
    '    sorted_names = sorted(name_to_code, key=lambda x: len(x[0]), reverse=True)',
    '    for name, code in sorted_names:',
    '        if len(name) >= 3 and name.lower() in q_lower:',
    '            return code',
    '',
    '    # Priority 4: Scan user_query directly for explicit 3-5 letter uppercase tickers in code_stock.csv',
    '    for w in re.findall(r"\\b[A-Za-z]{3,5}\\b", user_query):',
    '        w_up = w.upper()',
    '        if w_up in all_tickers and w_up not in NEGATIVE_BLOCKLIST:',
    '            return w_up',
    '',
    '    # Priority 5: Validate LLM-supplied company_input',
    '    if company_input:',
    '        c_upper = company_input.upper()',
    '        if c_upper in all_tickers and c_upper not in NEGATIVE_BLOCKLIST:',
    '            if c_upper.lower() in q_lower or c_upper in user_query:',
    '                return c_upper',
    '        c_lower = company_input.lower()',
    '        for name, code in sorted_names:',
    '            if len(name) >= 3 and (name.lower() in c_lower or c_lower in name.lower()):',
    '                if name.lower() in q_lower or code.lower() in q_lower:',
    '                    return code',
    '',
    '    if company_input and (company_input.upper() in NEGATIVE_BLOCKLIST or (company_input.lower() not in q_lower and company_input.upper() not in user_query)):',
    '        return ""',
    '',
    '    return company_input',
    '',
    '',
    'def _clean_financial_content(text: str) -> str:',
    '    """Clean action phrases, measurement prefixes, and query noise from financial content string."""',
    '    if not text:',
    '        return ""',
    '',
    '    cleaned = text.strip()',
    '',
    '    # Strip leading action/measurement phrases',
    '    strip_patterns = [',
    '        r"^tốc\\s+độ\\s+tăng\\s+trưởng\\s*%\\s*",',
    '        r"^tốc\\s+độ\\s+tăng\\s+trưởng\\s*",',
    '        r"^tăng\\s+trưởng\\s*%\\s*",',
    '        r"^tăng\\s+trưởng\\s*",',
    '        r"^tỷ\\s+lệ\\s+tăng\\s+trưởng\\s*",',
    '        r"^mức\\s+biến\\s+động\\s*",',
    '        r"^chênh\\s+lệch\\s*",',
    '        r"^so\\s+sánh\\s*",',
    '        r"^tính\\s+tổng\\s*",',
    '        r"^trích\\s+xuất\\s*",',
    '        r"^cho\\s+biết\\s*",',
    '        r"^số\\s+dư\\s+",',
    '        r"^tổng\\s+số\\s+",',
    '        r"^tổng\\s+giá\\s+trị\\s+",',
    '        r"^khoản\\s+",',
    '        r"^giá\\s+trị\\s+còn\\s+lại\\s+của\\s+",',
    '    ]',
    '',
    '    for pattern in strip_patterns:',
    '        cleaned = re.sub(pattern, "", cleaned, flags=re.IGNORECASE)',
    '',
    '    # Strip trailing question/noise phrases',
    '    trailing_patterns = [',
    '        r"\\s*là\\s+bao\\s+nhiêu\\??$",',
    '        r"\\s*bao\\s+nhiêu\\??$",',
    '        r"\\s*thay\\s+đổi\\s+như\\s+thế\\s+nào\\??$",',
    '        r"\\s*như\\s+thế\\s+nào\\??$",',
    '    ]',
    '    for pattern in trailing_patterns:',
    '        cleaned = re.sub(pattern, "", cleaned, flags=re.IGNORECASE)',
    '',
    '    return cleaned.strip()',
    '',
    '',
    'def _fallback_parse_query(user_query: str) -> Dict[str, Any]:',
    '    """Fallback rule-based parser when LLM is unreachable."""',
    '    q = user_query.strip()',
    '',
    '    # Check for range pattern e.g. "từ năm 2021 đến năm 2023" or "từ 2021 đến 2023"',
    '    range_match = re.search(r"từ\\s*(?:năm\\s*)?(\\d{4})\\s*đến\\s*(?:năm\\s*)?(\\d{4})", q, re.IGNORECASE)',
    '    if range_match:',
    '        y1, y2 = int(range_match.group(1)), int(range_match.group(2))',
    '        start_y, end_y = min(y1, y2), max(y1, y2)',
    '        years = [str(y) for y in range(start_y, end_y + 1)]',
    '        tieu_chi_phu = range_match.group(0)',
    '    else:',
    '        years = re.findall(r"\\b(20\\d{2})\\b", q)',
    '        tieu_chi_phu = None',
    '',
    '    q_lower = q.lower()',
    '    if "so sánh" in q_lower or "thay đổi" in q_lower or "tăng trưởng" in q_lower or "từ năm" in q_lower or "đến năm" in q_lower:',
    '        thao_tac = "so_sanh"',
    '    else:',
    '        thao_tac = "trich_xuat"',
    '',
    '    # Extract company / ticker',
    '    company = _normalize_company_name("", user_query)',
    '',
    '    clean_content = re.sub(r"\\b(20\\d{2})\\b", "", q)',
    '    if company:',
    '        clean_content = re.sub(rf"\\b{company}\\b", "", clean_content, flags=re.IGNORECASE)',
    '',
    '    # Remove growth/comparison stop words',
    '    stop_phrases = [',
    '        "tốc độ tăng trưởng %", "tốc độ tăng trưởng", "tăng trưởng %", "tăng trưởng",',
    '        "so sánh", "từ năm", "đến năm", "của", "năm", "báo cáo", "tài chính",',
    '        "cho", "là bao nhiêu", "bao nhiêu"',
    '    ]',
    '    for word in stop_phrases:',
    '        clean_content = re.sub(rf"\\b{re.escape(word)}\\b", "", clean_content, flags=re.IGNORECASE)',
    '',
    '    clean_content = _clean_financial_content(clean_content or q)',
    '',
    '    return {',
    '        "ticker": company,',
    '        "ten_cong_ty": company,',
    '        "year": ", ".join(years),',
    '        "so_nam": years,',
    '        "metric": clean_content or q,',
    '        "noi_dung": clean_content or q,',
    '        "thao_tac": thao_tac,',
    '        "muc_tieu": thao_tac,',
    '        "tieu_chi_phu": tieu_chi_phu,',
    '    }',
    '',
    '',
    'def parse_query_node(state: AgentState, cfg: Optional[Config] = None) -> AgentState:',
    '    """LangGraph Node 1: Phân tích câu hỏi thành cấu trúc truy vấn.',
    '',
    '    Trích xuất: ten_cong_ty, so_nam, noi_dung, thao_tac (muc_tieu: trich_xuat | so_sanh), tieu_chi_phu.',
    '    KHÔNG tìm bảng — Data Discovery sẽ xử lý.',
    '',
    '    Args:',
    '        state: Current AgentState containing \'user_query\'',
    '        cfg: Config instance (defaults to global config)',
    '',
    '    Returns:',
    '        Updated AgentState with \'parsed_query\', \'status\', and latency tracking.',
    '    """',
    '    cfg = cfg or default_config',
    '    start_time = time.time()',
    '    user_query = state.get("user_query", "").strip()',
    '',
    '    if not user_query:',
    '        return {',
    '            **state,',
    '            "status": "error",',
    '            "error_message": "User query is empty.",',
    '            "parsed_query": {},',
    '        }',
    '',
    '    try:',
    '        # Load prompts',
    '        prompt_data = load_query_parser_prompt(cfg)',
    '        system_prompt = prompt_data["system_prompt"]',
    '        json_schema = prompt_data["json_schema"]',
    '        few_shots = prompt_data.get("few_shot_examples", [])',
    '',
    '        # Build prompt messages',
    '        prompt_messages = [',
    '            SystemMessage(content=f"{system_prompt}\\n\\nSchema Yêu cầu:\\n{json_schema}")',
    '        ]',
    '',
    '        for example in few_shots:',
    '            prompt_messages.append(HumanMessage(content=example["user_query"]))',
    '            prompt_messages.append(SystemMessage(content=example["parsed_output"]))',
    '',
    '        prompt_messages.append(HumanMessage(content=f"Câu hỏi: {user_query}"))',
    '',
    '        # Call LLM with slight temperature=0.1 to avoid overfitting/copy-pasting examples',
    '        llm = get_llm(cfg=cfg, temperature=0.1)',
    '        response = llm.invoke(prompt_messages)',
    '',
    '        raw_content = response.content if isinstance(response.content, str) else str(response.content)',
    '',
    '        # Extract and print agent thoughts',
    '        print(f"\\n🔍 [Query Parser] Đang phân tích câu hỏi: \'{user_query}\'")',
    '        think_match = re.search(r"<think>(.*?)</think>", raw_content, re.DOTALL)',
    '        if think_match:',
    '            thought = think_match.group(1).strip()',
    '            indented_thought = thought.replace("\\n", "\\n  ")',
    '            print(f"💭 [Tư duy - Query Parser]:\\n  {indented_thought}")',
    '        else:',
    '            json_start = raw_content.find("{")',
    '            if json_start > 10:',
    '                thought = raw_content[:json_start].strip()',
    '                indented_thought = thought.replace("\\n", "\\n  ")',
    '                print(f"💭 [Tư duy - Query Parser]:\\n  {indented_thought}")',
    '',
    '        # Parse output JSON',
    '        parsed_json = safe_parse_json(raw_content)',
    '',
    '        # Map strict schema keys {\\"ticker\\", \\"year\\", \\"metric\\"} to state schema keys',
    '        raw_ticker_val = parsed_json.get("ticker") or parsed_json.get("ten_cong_ty") or ""',
    '        metric_val = parsed_json.get("metric") or parsed_json.get("noi_dung") or ""',
    '        year_val = parsed_json.get("year") if "year" in parsed_json else parsed_json.get("so_nam")',
    '',
    '        # Fallback year extraction from query if year is None or empty',
    '        if not year_val or year_val is None or str(year_val).strip() in ["None", "null", ""]:',
    '            year_val = re.findall(r"\\b(20\\d{2})\\b", user_query)',
    '',
    '        # Ensure so_nam is a list of strings',
    '        if isinstance(year_val, str):',
    '            so_nam_list = [y.strip() for y in year_val.replace(",", " ").split() if y.strip().isdigit()]',
    '            if not so_nam_list:',
    '                so_nam_list = re.findall(r"\\b(20\\d{2})\\b", user_query)',
    '        elif isinstance(year_val, (int, float)):',
    '            so_nam_list = [str(int(year_val))]',
    '        elif isinstance(year_val, list):',
    '            so_nam_list = [str(y).strip() for y in year_val if str(y).strip().isdigit()]',
    '        else:',
    '            so_nam_list = re.findall(r"\\b(20\\d{2})\\b", user_query)',
    '',
    '        # Synchronize ticker / ten_cong_ty strictly',
    '        resolved_ticker = _normalize_company_name(raw_ticker_val, user_query)',
    '        parsed_json["ticker"] = resolved_ticker',
    '        parsed_json["ten_cong_ty"] = resolved_ticker',
    '        parsed_json["year"] = ", ".join(so_nam_list) if so_nam_list else ""',
    '        parsed_json["so_nam"] = so_nam_list',
    '',
    '        # Ensure minimal structure and sync thao_tac / muc_tieu (only trich_xuat or so_sanh)',
    '        thao_tac = parsed_json.get("thao_tac") or parsed_json.get("muc_tieu") or (',
    '            "so_sanh" if len(so_nam_list) > 1 or "so sánh" in user_query.lower() or "tăng trưởng" in user_query.lower() else "trich_xuat"',
    '        )',
    '        if thao_tac not in ["trich_xuat", "so_sanh"]:',
    '            thao_tac = "trich_xuat"',
    '',
    '        parsed_json["thao_tac"] = thao_tac',
    '        parsed_json["muc_tieu"] = thao_tac',
    '',
    '        # Clean metric / noi_dung using _clean_financial_content',
    '        cleaned_content = _clean_financial_content(metric_val) or metric_val',
    '        parsed_json["metric"] = cleaned_content',
    '        parsed_json["noi_dung"] = cleaned_content',
    '',
    '        if "tieu_chi_phu" not in parsed_json:',
    '            parsed_json["tieu_chi_phu"] = None',
    '',
    '        print(',
    '            f"📊 [Kết quả - Query Parser]:\\n"',
    '            f"   Công ty: {parsed_json.get(\'ten_cong_ty\')}\\n"',
    '            f"   Năm: {parsed_json.get(\'so_nam\')}\\n"',
    '            f"   Nội dung: {parsed_json.get(\'noi_dung\')}\\n"',
    '            f"   Thao tác: {parsed_json.get(\'thao_tac\')}\\n"',
    '            f"   Tiêu chí phụ: {parsed_json.get(\'tieu_chi_phu\')}\\n"',
    '        )',
    '',
    '        latency = time.time() - start_time',
    '        node_latencies = state.get("node_latencies", {})',
    '        node_latencies["query_parser"] = round(latency, 3)',
    '',
    '        return {',
    '            **state,',
    '            "parsed_query": parsed_json,',
    '            "status": "pending",',
    '            "node_latencies": node_latencies,',
    '        }',
    '',
    '    except Exception as e:',
    '        print(f"⚠️ [Query Parser] LLM không phản hồi ({e}). Đang sử dụng Rule-based Fallback Parser...")',
    '        parsed_json = _fallback_parse_query(user_query)',
    '',
    '        latency = time.time() - start_time',
    '        node_latencies = state.get("node_latencies", {})',
    '        node_latencies["query_parser"] = round(latency, 3)',
    '',
    '        print(',
    '            f"📊 [Kết quả Fallback - Query Parser]:\\n"',
    '            f"   Công ty: {parsed_json.get(\'ten_cong_ty\')}\\n"',
    '            f"   Năm: {parsed_json.get(\'so_nam\')}\\n"',
    '            f"   Nội dung: {parsed_json.get(\'noi_dung\')}\\n"',
    '            f"   Thao tác: {parsed_json.get(\'thao_tac\')}\\n"',
    '            f"   Tiêu chí phụ: {parsed_json.get(\'tieu_chi_phu\')}\\n"',
    '        )',
    '',
    '        return {',
    '            **state,',
    '            "parsed_query": parsed_json,',
    '            "status": "pending",',
    '            "node_latencies": node_latencies,',
    '        }',
]

with open("pipeline/src/nodes/query_parser.py", "w", encoding="utf-8") as f:
    f.write("\n".join(code_lines) + "\n")
print("Successfully written query_parser.py from code_lines!")
